
services:
  mamar_bank:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mamar_bank
    ports:
      - "8001:8001"
    command: >
      sh -c "until pg_isready -h postgres -p 5432 -U postgres; do sleep 1; done &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8001"
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    networks:
      - mamar_bank_net

  postgres:
    image: postgres:16-alpine
    container_name: mamar_bank_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: mamar_bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - mamar_bank_net


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mamar_bank_pgadmin
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - mamar_bank_net

  redis:
    image: redis:alpine
    container_name: mamar_bank_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 500mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mamar_bank_net


  # Celery Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mamar_bank_worker
    command: celery -A Mamar_Bank worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - redis
      - mamar_bank
    networks:
      - mamar_bank_net


volumes:
  redis_data:
  pgadmin_data:
  postgres_data:


networks:
  mamar_bank_net:
    driver: bridge

