services:
  postgres:
    image: postgres:16-alpine
    container_name: mamar_bank_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: mamar_bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mamar_bank_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - mamar_bank_net


  redis:
    image: redis:alpine
    container_name: mamar_bank_redis
    command: redis-server --appendonly yes --maxmemory 500mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - mamar_bank_net


  mamar_bank:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mamar_bank
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8001
      "
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mamar_bank_net
    expose:
      - "8001"   # ðŸ‘ˆ internal only


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mamar_bank_worker
    command: celery -A Mamar_Bank worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mamar_bank_net


  nginx:
    image: nginx:alpine
    container_name: mamar_bank_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      mamar_bank:
        condition: service_started
    restart: unless-stopped
    networks:
      - mamar_bank_net


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mamar_bank_pgadmin
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mamar_bank_net


volumes:
  postgres_data:
  redis_data:
  pgadmin_data:


networks:
  mamar_bank_net:
    driver: bridge
